<html>
<head>
<title>Exception Handling in Java</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Java中的异常处理</h1>
<blockquote>原文：<a href="https://medium.com/javarevisited/exception-handling-in-java-89e4b292626f?source=collection_archive---------3-----------------------#2021-09-29">https://medium.com/javarevisited/exception-handling-in-java-89e4b292626f?source=collection_archive---------3-----------------------#2021-09-29</a></blockquote><div><div class="ds gw gx gy gz ha"/><div class="hb hc hd he hf"><div class=""/></div><div class="ab cl if ig gp ih" role="separator"><span class="ii bw bk ij ik il"/><span class="ii bw bk ij ik il"/><span class="ii bw bk ij ik"/></div><div class="hb hc hd he hf"><p id="4296" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">异常是运行代码时发生的不需要的事件。</p><p id="c2a5" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">下面是Java中的类层次结构:</p><figure class="jl jm jn jo fd jp er es paragraph-image"><div role="button" tabindex="0" class="jq jr di js bf jt"><div class="er es jk"><img src="../Images/0c9bbb55b70866d7b9cb2c44ff5e2e4d.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*qeiySVqYDwLfpKOt2u8QjA.png"/></div></div></figure><p id="96fb" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">基本思想是:<strong class="io hj"> try </strong>会有可能抛出错误的业务逻辑。<strong class="io hj"> catch </strong>块有处理和捕捉异常的代码。<strong class="io hj">最后</strong>块用于清理目的，如关闭流、关闭文件、删除文件。</p><h1 id="a69f" class="jw jx hi bd jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt bi translated">尝试捕捉块:</h1><p id="8271" class="pw-post-body-paragraph im in hi io b ip ku ir is it kv iv iw ix kw iz ja jb kx jd je jf ky jh ji jj hb bi translated">下面的代码在编译期间给出了一个错误。原因是createFile()是java.io.File包的一个方法，它在内部抛出一个异常。</p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="c076" class="le jx hi la b fi lf lg l lh li">public class DemoException {<br/>    static DemoException <em class="lj">demoException</em>;<br/><br/>    public static void main(String args[]) throws IOException {<br/>        <em class="lj">demoException </em>= new DemoException();<br/>        <em class="lj">demoException</em>.createFile();<br/>    }<br/>    void createFile() {<br/>        File myFile = null;<br/>        myFile = new File("newFile.txt");<br/>        System.<em class="lj">out</em>.println(myFile.getAbsolutePath());<br/>        if (myFile.createNewFile()) {<br/>            System.<em class="lj">out</em>.println("File is created!");<br/>        } else {<br/>            System.<em class="lj">out</em>.println("File already exists.");<br/>        }<br/>    }<br/>}</span></pre><p id="bb13" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">有两种方法可以修复编译时问题:<br/> <br/> 1。Add在方法定义行中引发IOException</p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="a17f" class="le jx hi la b fi lf lg l lh li">void createFile() <strong class="la hj">throws IOException</strong> {<br/>    File myFile = null;<br/>    myFile = new File("newFile.txt");<br/>    System.<em class="lj">out</em>.println(myFile.getAbsolutePath());<br/>    if (myFile.createNewFile()) {<br/>        System.<em class="lj">out</em>.println("File is created!");<br/>    } else {<br/>        System.<em class="lj">out</em>.println("File already exists.");<br/>    }<br/>}</span></pre><p id="d4d5" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">2.使用try catch块</p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="3930" class="le jx hi la b fi lf lg l lh li">void createFile() {<br/>    <strong class="la hj">try</strong> {<br/>        File myFile = null;<br/>        myFile = new File("newFile.txt");<br/>        System.<em class="lj">out</em>.println(myFile.getAbsolutePath());<br/>        if (myFile.createNewFile()) {<br/>            System.<em class="lj">out</em>.println("File is created!");<br/>        } else {<br/>            System.<em class="lj">out</em>.println("File already exists.");<br/>        }<br/>    } <strong class="la hj">catch</strong> (Exception e) {<br/>        System.<em class="lj">out</em>.println("An exception was thrown" + e);<br/>    }<br/>}</span></pre><p id="8fa6" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">因此，当您调用任何方法时，如果它抛出一个错误，您将不得不在方法定义中或者用try catch块来捕获异常。</p><p id="eea5" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">下面是一个例子:</p><p id="2d73" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">下面的代码将再次给出一个编译器异常，因为fileOperations方法不处理createFile()抛出的异常。</p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="520d" class="le jx hi la b fi lf lg l lh li">public class DemoException {<br/>    <br/>    public static void main(String args[]) {<br/>        <em class="lj">fileOperations</em>();<br/>    }<br/>    static void fileOperations() {<strong class="la hj"> <br/>            // compile time issue as exception is not handled<br/>            File file = <em class="lj">createFile</em>();</strong><br/>    }<br/>    static File createFile() throws IOException {<br/>        File myFile = null;<br/>        try {<br/>            myFile = new File("newFile.txt");<br/>            System.<em class="lj">out</em>.println(myFile.getAbsolutePath());<br/>            if (myFile.createNewFile()) {<br/>                System.<em class="lj">out</em>.println("File is created!");<br/>            } else {<br/>                System.<em class="lj">out</em>.println("File already exists.");<br/>            }<br/>        } catch(Exception e) {<br/>            System.<em class="lj">out</em>.println("An exception catched :" +e);<br/>            throw new IOException();<br/>        }<br/>        return myFile;<br/>    }<br/>}</span></pre><p id="b237" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">正确的解决方案是在方法定义中使用try catch或throws异常，如下所示:</p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="5ebc" class="le jx hi la b fi lf lg l lh li">static void fileOperations() {<br/>   <strong class="la hj"> try</strong> {<br/>        File file = <em class="lj">createFile</em>();<br/>    } <strong class="la hj">catch</strong> (Exception e) {<br/><br/>    }<br/>}</span></pre><p id="5ccf" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">或者</p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="33fb" class="le jx hi la b fi lf lg l lh li">static void fileOperations() <strong class="la hj">throws IOException</strong>{<br/>        File file = <em class="lj">createFile</em>();<br/>}</span></pre><h1 id="0570" class="jw jx hi bd jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt bi translated"><strong class="ak">尝试使用资源:</strong></h1><p id="6cbf" class="pw-post-body-paragraph im in hi io b ip ku ir is it kv iv iw ix kw iz ja jb kx jd je jf ky jh ji jj hb bi translated">基本上，try with resources用于消除使用额外的finally块来关闭文件或流的复杂性。JVM保证，一旦try块执行完成，资源将被关闭。</p><p id="ea1c" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated"><em class="lj">一个try catch最后的格式:</em></p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="84e8" class="le jx hi la b fi lf lg l lh li">public class DemoException {<br/><br/>    public static void main(String args[]) {<br/>        <em class="lj">method</em>();<br/>    }<br/>    static void method() {<br/>        try{ <br/>            // open a file<br/>            // open a file stream<br/>        } catch(Exception e) {<br/>            <br/>        } finally {<br/>            //close the file and the file stream<br/>        }<br/>        <br/>    }<br/>}</span></pre><p id="1da4" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">如果我们必须使用try with resources做同样的事情，那么我们将不会使用finally，因为一旦try块执行完毕，默认情况下JVM将关闭try使用的流和文件。</p><p id="64a1" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated"><strong class="io hj">资源试用格式:</strong></p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="887b" class="le jx hi la b fi lf lg l lh li">public class DemoException {<br/><br/>    public static void main(String args[]) {<br/>        <em class="lj">method</em>();<br/>    }<br/>    static void method() {<br/>        <strong class="la hj">try()</strong>{<br/>            // business logic<br/>        } catch(Exception e) {<br/><br/>        } <br/><br/>    }<br/>}</span></pre><p id="c161" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">上面用粗体标记了代码，这是我们需要编写代码来打开任何资源(如文件和流)的地方。</p><p id="7f19" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">尝试使用资源的示例:</p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="0ea0" class="le jx hi la b fi lf lg l lh li"><br/>import java.io.File;<br/>import java.io.FileOutputStream;<br/>import java.io.IOException;<br/>import java.io.OutputStream;<br/>import java.util.logging.Level;<br/>import java.util.logging.Logger;<br/><br/>public <strong class="la hj">class DemoException</strong> {<br/>    <br/>    static DemoException <em class="lj">demoException</em>;<br/><br/>    private static final Logger <em class="lj">LOGGER </em>=  Logger.<br/>                 <em class="lj">getLogger</em>(Logger.<em class="lj">GLOBAL_LOGGER_NAME</em>);</span><span id="6a94" class="le jx hi la b fi lk lg l lh li">    <strong class="la hj">public static void main</strong>(String args[]) throws IOException {<br/>        <em class="lj">demoException </em>= new DemoException();<br/>        <strong class="la hj"><em class="lj">demoException</em>.fileOperations</strong>();<br/>    }</span><span id="ccf2" class="le jx hi la b fi lk lg l lh li">    void <strong class="la hj">fileOperations</strong>() {<br/>        try {<br/>            File file = <em class="lj">demoException</em>.<strong class="la hj">createFile</strong>();<br/>            <em class="lj">demoException</em>.<strong class="la hj">openOutputStream</strong>(file);<br/>        } catch (Exception e) {<br/>            <em class="lj">LOGGER</em>.log(Level.<em class="lj">WARNING</em>, "Error in file");<br/>        }<br/>    }</span><span id="7878" class="le jx hi la b fi lk lg l lh li">    File <strong class="la hj">createFile</strong>() {<br/>        File myFile = null;<br/>        try {<br/>            myFile = new File("newFile.txt");<br/>            System.<em class="lj">out</em>.println(myFile.getAbsolutePath());<br/>            if (myFile.createNewFile()) {<br/>                System.<em class="lj">out</em>.println("File is created!");<br/>            } else {<br/>                System.<em class="lj">out</em>.println("File already exists.");<br/>            }<br/>        } catch(Exception e) {<br/>            <em class="lj">LOGGER</em>.log(Level.<em class="lj">WARNING</em>, "Error in creating file");<br/>        }<br/>        return myFile;<br/>    }<br/>    void <strong class="la hj">openOutputStream</strong>(File file) throws IOException {<br/>        <strong class="la hj">try (<em class="lj">OutputStream out = new FileOutputStream(file)</em>)</strong> {<br/>            write(out);<br/>            System.<em class="lj">out</em>.println("Output Stream");<br/>        }<br/>    }<br/>    void <strong class="la hj">write</strong>(OutputStream out) throws IOException {<br/>        throw new IOException();<br/>    }<br/>}</span><span id="0c93" class="le jx hi la b fi lk lg l lh li">Outputs an exception. write() throws an exception. The exception is then catched by openOutputStream(). openOutputStream although doesn't have a catch block, throws an exception to fileOperations(), which is catched and then on console we see an exception logged. <br/>Outputs : WARNING: Error in file</span></pre><p id="73e2" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">如果您看到上面的代码，<strong class="io hj"> try with resources(用粗体标记)没有catch块，它在内部负责捕捉异常并将异常抛出给方法的调用方。</strong></p><h1 id="3a3b" class="jw jx hi bd jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt bi translated">for循环的异常处理:</h1><p id="97a3" class="pw-post-body-paragraph im in hi io b ip ku ir is it kv iv iw ix kw iz ja jb kx jd je jf ky jh ji jj hb bi translated">如果运行下面的代码，控制台上会显示什么？</p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="6be0" class="le jx hi la b fi lf lg l lh li">public class DemoException {<br/>    public static void main(String args[]) {<br/>        for(int i = 0; i&lt;10;i++) {<br/>            try {<br/>                throw new RuntimeException();<br/>            } catch (Exception e) {<br/>                System.<em class="lj">out</em>.println("Error thrown" +e);<br/>            }<br/>        }<br/>    }<br/>}</span></pre><p id="e5b2" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">这些选项包括:</p><ol class=""><li id="2bba" class="ll lm hi io b ip iq it iu ix ln jb lo jf lp jj lq lr ls lt bi translated">只打印一次异常</li><li id="9954" class="ll lm hi io b ip lu it lv ix lw jb lx jf ly jj lq lr ls lt bi translated">将异常打印10次</li></ol><p id="1fa1" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated"><strong class="io hj">的答案是</strong> —它将<strong class="io hj">打印10次</strong>的异常，因为我们正在处理for循环中的所有异常。</p><p id="bd61" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">但是，如果我们在catch块中专门抛出一个异常，那么用粗体标记的错误抛出语句将只打印一次。</p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="1d5e" class="le jx hi la b fi lf lg l lh li">public class DemoException {<br/>    public static void main(String args[]) {<br/>        for(int i = 0; i&lt;10;i++) {<br/>            try {<br/>                throw new RuntimeException();<br/>            } catch (Exception e) {<br/>                <strong class="la hj">System.<em class="lj">out</em>.println("Error thrown" +e);</strong><br/>                throw new RuntimeException();<br/>            }<br/>        }<br/>    }<br/>}</span></pre><p id="73e5" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated">现在，如果我们在for循环之外使用了try catch块，那么“Error thrown”也只打印一次。</p><pre class="jl jm jn jo fd kz la lb lc aw ld bi"><span id="b1d6" class="le jx hi la b fi lf lg l lh li">public class DemoException {<br/>    public static void main(String args[]) {<br/>        try {<br/>            for (int i = 0; i &lt; 10; i++) {<br/>                throw new RuntimeException();<br/>            }<br/>        } catch (Exception e) {<br/>            System.<em class="lj">out</em>.println("Exception thrown" +e);<br/>        }<br/>    }<br/>}</span></pre><p id="8000" class="pw-post-body-paragraph im in hi io b ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj hb bi translated"><strong class="io hj">结论:<br/> </strong>希望这些实际例子涵盖了我们在日常工作中遇到的所有基本场景。如果你认为我可以添加更多的细节，或者你有任何特定的使用案例，请告诉我。</p></div></div>    
</body>
</html>